### ISSUE TITLE
Detectable viral result is not registering once entered and saved in the form

### ISSUE THREAD

**Issue by ceciliahnjenga** [uon-crissp/IQCare#42]
- When a detectable VL value is entered into the results section, along with other entries on the form, the VL results particularly is not saved in the system.

-VL result should save both in the lab result history as well as the slider.

**Comment by LydiaKiragu** [comment]
This issue has been reviewed and identified as a *BUG*. 

It should take about 48 business hours to resolve.

**Comment by kenkirui** [comment]
@ceciliahnjenga , this issue has been resolved. This issue was as a result of a wrong data type specified for Viral Load test i.e. data type specified as TEXT instead of NUMERIC
