### ISSUE TITLE
Populating new drug stock

### ISSUE THREAD

**Issue by LydiaKiragu** [uon-crissp/IQCare#48]
- Pharmacy is unable to populate a new drug stock in the supply chain module. Batch numbers for new drugs entered in in the system not showing uo when Rx is being dispensed.

- Would like to be able to enter new drugs into the system so that we can dispense the drugs Rx.  

FYI: Issue reported by Derrick Munene Pharmacist - Kigumo

**Comment by kenkirui** [comment]
We will check out this issue today

**Comment by ElphasKimutai** [comment]
Thank for sorting out.

**Comment by kiambupharmacy** [comment]
Please resolve this issue for Kiambu County Referral pharmacy - Specific Drugs missing in the system:
 - Raltegravir 400mg
- Kaletra pellets 40/10mg caps
- Dolutegravir 50mg

Reported by Rita

**Comment by LydiaKiragu** [comment]
This Issue was sorted Jul 2nd by Ken Kirui.
